# Generated by Django 4.2.26 on 2025-11-06 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0002_userprofile_created_at_userprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='detection_images/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='detection_images/processed/')),
                ('detection_results', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('objects_detected', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'obraz do detekcji',
                'verbose_name_plural': 'obrazy do detekcji',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
